# Generated by Django 5.0.4 on 2025-01-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_files_file_alter_files_name_alter_files_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ftype',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='files',
            name='parent',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
