# Generated by Django 5.0.4 on 2025-02-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_class_users_class_under'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='class_under',
        ),
    ]
