# Generated by Django 5.0.4 on 2025-02-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_files_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_size',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
