# Generated by Django 5.0.4 on 2025-02-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_files_file_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('rtype', models.CharField(choices=[('Teaching', 'Teaching'), ('Non Teaching', 'Non Teaching'), ('Guest', 'Guest'), ('Other', 'Other')], max_length=15)),
            ],
        ),
    ]
