# Generated by Django 5.0.4 on 2025-02-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='classfor',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
