# Generated by Django 5.0.4 on 2025-02-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_delete_storage_users_max_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='max_storage',
            field=models.IntegerField(choices=[('5GB', 500000), ('15GB', 1500000), ('50GB', 5000000), ('100GB', 10000000)], default=0),
        ),
    ]
