# Generated by Django 5.0.4 on 2025-02-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0020_alter_users_max_storage'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='sizeinkb',
            field=models.IntegerField(default=0),
        ),
    ]
