from .profile import *
from .dashboard import *
from .students import *
from .staff import *
from .settings import *
from .reports import *
from .uploadfile import *
from .cloud import *
from .home import *
from .authentication import *
